---
title: " "
---

<br>

<center>
# Rosvid Steven Herrera Tenorio (He/Him/His)
</center>

***

<br>

I am a second-year Ph.D. student at the University of California, Berkeley in the joint Ph.D. program in Sociology and Demography. My research interests include acculturation, assimilation, and integration theory, racial stratification, migration, demography, and quantitative methods. I was born in Guatemala, grew up in rural North Carolina, and now live in Berkeley, California. I received my undergraduate degree in Statistical Science from Duke University in 2021.

<br>

~~When I am not coding, reading, or completing coursework, I am exploring San Francisco, playing tennis, or Facetiming my dogs in North Carolina.~~ I love my dogs. 
 

I almost always coding, reading, or completing coursework.

<br>

<center>
The code to make this website is [here](https://github.com/stevenherrera24/stevenherrera24.github.io). To contact me, click [here](https://stevenherreratenorio.com/contact.html). Last update: September 22, 2022
</center>
